# spring:
#   datasource:
#     url: jdbc:sqlserver://server-db01.database.windows.net:1433;database=employee;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#     username: shubhendu027
#     password: password@123
#   jpa:
#     show-sql: true 
#     hibernate:
#       ddl-auto: update
#       dialect: org.hibernate.dialect.SQLServer2012Dialect
      
      
server:
  port: 9191

   
